[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc", "gnumake", "pkg-config", "glibc", "stdenv"]

[phases.install]
cmds = [
  "export CC=gcc",
  "export CXX=g++",
  "npm ci --verbose"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"
